### ISSUE TITLE
How to set up API key?

### ISSUE THREAD

**Issue by adhi-r** [dietrichson/ProPublicaR#14]
I filled out the propublica form to get the Congress API key, but it's not clear to me how to set up the package to use the key so I can get up and running with the functions. Couldn't find any vignette or quick start guide - could I get some help? Thanks.

**Comment by dietrichson** [comment]
There are two ways:

You can pass the key as a parameter to the different functions. 

You can add it to a config.yml file like so:
default:
 ProPublica:
   API: mykey123456789
