### ISSUE TITLE
116th Congress

### ISSUE THREAD

**Issue by jsowder** [dietrichson/ProPublicaR#4]
Package does not allow querying the current 116th Congress (as well as future congresses moving forward). Currently returns error: "Incorrect congress. Should be 105 to 115"

**Comment by dietrichson** [comment]
Some of this had been corrected in the dev-version (install from GitHub). I
just haven't had a chance to republish on CRAN. I'll take another look
today to check it out.

**Comment by jsowder** [comment]
Thanks! Good deal. Seeing the fix in some of the functions now. I'm happy to jump in and make the fix in other functions

**Comment by dietrichson** [comment]
I think we should refactor this a little bit. The way it works now it is
"semi-hardcoded", but we should in fact define it as a constant (i.e.
variable inside the package), as this would allow for a one-line update
come 2021.

If you want to do #5 (send me the link to your fork if you cannot do a PR)
I can take care of this one.

**Comment by jsowder** [comment]
Good deal. Just submitted the pull request on #5 after giving up on using the command line to do everything haha. Maybe next time! And thanks again for the great package, it's a huge help

**Comment by dietrichson** [comment]
@jsowder This should be updated now. I have also bumped the version number. Feel free to reinstall from github and try it out.
