### ISSUE TITLE
"Both" chambers option not supported

### ISSUE THREAD

**Issue by jsowder** [dietrichson/ProPublicaR#5]
Some API endpoints support "both" chambers of congress rather than just "house" or "senate". The package does not currently support this option and requires _either_ "house" or "senate".

(love the package by the way, looking to provide fixes for these myself if I can figure it out. thank you for laying the groundwork)

**Comment by dietrichson** [comment]
@jsowder can you specify the APIs. Sounds like an easy fix.

**Comment by jsowder** [comment]
Sure thing, it's the get_recent_bills_by_type function that allows for it. Made the fix in my forked version! 

Unfortunately I'm still very new to GitHub so I can't figure out how to submit the Pull request with the fix from my fork.

Thanks for the quick response!
